name: Detect Documentation Updates

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.js'  # Detects changes in JavaScript documentation files

jobs:
  notify-website-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Website Repo
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/YOUR_GITHUB_USERNAME/website-test/dispatches \
          -d '{"event_type": "docs_updated"}'
