name: Detect Documentation Updates

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.js'  # Detects changes in JavaScript documentation files
  workflow_dispatch:  # Allows manual trigger

jobs:
  notify-website-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Website Repo
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $PAT" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Ruchit-kumar44/test-p5.js-website/dispatches \
          -d '{"event_type": "docs_updated"}'
